// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/note.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2878562167716987067),
      name: 'Note',
      lastPropertyId: const obx_int.IdUid(10, 9157536747027021073),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3138074035479813976),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6578191507565643618),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 1818667497919414839)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1440214946261172328),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6314040471328157529),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5083135719891796167),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8406353866869976139),
            name: 'isPinned',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4989148917180783120),
            name: 'isArchived',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1557378662760537821),
            name: 'isBold',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8420008247863072605),
            name: 'isItalic',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 9157536747027021073),
            name: 'isUnderlined',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 2878562167716987067),
      lastIndexId: const obx_int.IdUid(1, 1818667497919414839),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Note: obx_int.EntityDefinition<Note>(
        model: _entities[0],
        toOneRelations: (Note object) => [],
        toManyRelations: (Note object) => {},
        getId: (Note object) => object.objectBoxId,
        setId: (Note object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (Note object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(11);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
          fbb.addBool(5, object.isPinned);
          fbb.addBool(6, object.isArchived);
          fbb.addBool(7, object.isBold);
          fbb.addBool(8, object.isItalic);
          fbb.addBool(9, object.isUnderlined);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final objectBoxIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final isPinnedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final isArchivedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final isBoldParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final isItalicParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final isUnderlinedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);
          final object = Note(
              objectBoxId: objectBoxIdParam,
              id: idParam,
              content: contentParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              isPinned: isPinnedParam,
              isArchived: isArchivedParam,
              isBold: isBoldParam,
              isItalic: isItalicParam,
              isUnderlined: isUnderlinedParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.objectBoxId].
  static final objectBoxId =
      obx.QueryIntegerProperty<Note>(_entities[0].properties[0]);

  /// See [Note.id].
  static final id = obx.QueryStringProperty<Note>(_entities[0].properties[1]);

  /// See [Note.content].
  static final content =
      obx.QueryStringProperty<Note>(_entities[0].properties[2]);

  /// See [Note.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Note>(_entities[0].properties[3]);

  /// See [Note.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<Note>(_entities[0].properties[4]);

  /// See [Note.isPinned].
  static final isPinned =
      obx.QueryBooleanProperty<Note>(_entities[0].properties[5]);

  /// See [Note.isArchived].
  static final isArchived =
      obx.QueryBooleanProperty<Note>(_entities[0].properties[6]);

  /// See [Note.isBold].
  static final isBold =
      obx.QueryBooleanProperty<Note>(_entities[0].properties[7]);

  /// See [Note.isItalic].
  static final isItalic =
      obx.QueryBooleanProperty<Note>(_entities[0].properties[8]);

  /// See [Note.isUnderlined].
  static final isUnderlined =
      obx.QueryBooleanProperty<Note>(_entities[0].properties[9]);
}
